project:
  type: website

website:
  title: "Documentación"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - java.qmd
      - mindset.qmd
      - git.qmd
      - react.qmd
      - devop.qmd
      - proyectopersonal.qmd
      - scrum.qmd
      - quarto.qmd
      - about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true



